routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::middleware('auth')->group(function (){
	Route::resource('tickets','TicketController');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    
}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    public function comments()
    {
    	return $this->hasMany(Comment::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /*Get ticket for current user*/
    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Ticket;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return redirect()->route('tickets.index');
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Ticket;
use App\Http\Requests\NewTicketRequest;

class TicketController extends Controller
{
    public function __construct()
    {

    }

    public function index(Request $request)
    {
    	$status     = ($request->get('status') != '') ? $request->get('status') : 'open'; 
        $tickets    = Auth::user()->tickets()->whereStatus($status)->get();
        return view('tickets.index',compact('tickets'));
    }

    public function create(Request $request)
    {
    	return view('tickets.create');
    }

    public function edit($ticket,Request $request)
    {
    	return view('tickets.edit',compact('ticket'));
    }

    public function store(NewTicketRequest $request)
    {  
    	$ticket                = new Ticket;
        $ticket->title         = $request->get('title');
        $ticket->description   = $request->get('description');
        $ticket->status        = 'open';
        $ticket->user_id       = Auth::user()->id;
        $ticket->save();
        return redirect()->route('tickets.index');
    }

    public function update($ticket,NewTicketRequest $request)
    {
        $action                 = $request->get('action');
    	$ticket->title          = $request->get('title') ?: $ticket->title;
        $ticket->description    = $request->get('description') ?: $ticket->description;
        $ticket->status         = $request->get('status') ?: $ticket->status;
        return ($action == 'ajax') ? response()->json(['success'=>$ticket->save(),'data'=>$ticket]) : redirect()->route('tickets.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">My Tickets</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

        <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/tickets.js') }}"></script>
</body>
</html>

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Create New Ticket &nbsp; <a href="{{route('tickets.index')}}" class="btn btn-default btn-sm" style="float: right;"><i class="fa fa-tasks"></i> Manage Tickets</a>
                </div>

                <div class="card-body">
                   <form method="post" action="{{route('tickets.store')}}" class="form form-striped">
                    @csrf
                      <div class="form-group">
                        <label for="title">Title</label>
                        <input class="form-control" id="title" name="title" aria-describedby="emailHelp" value="{{old('title')}}">
                        @if ($errors->has('title'))
                            <span class="invalid-feedback" role="alert" style="display: block;">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                      </div>
                      <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" id="description" name="description">{{old('description')}}</textarea>
                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert" style="display: block;">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                      </div>

                      <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tickets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit Ticket #{{$ticket->id}}&nbsp; <a href="{{route('tickets.index')}}" class="btn btn-default btn-sm" style="float: right;"><i class="fa fa-tasks"></i> Manage Tickets</a>
                </div>

                <div class="card-body">
                   <form id="editTicketForm" method="post" action="{{route('tickets.update',['ticket'=>$ticket])}}" class="form form-striped">
                    @csrf
                    <input type="hidden" name="_method" value="PUT">
                      <div class="form-group">
                        <label for="title">Title</label>
                        <input class="form-control" id="title" name="title" aria-describedby="emailHelp" value="{{old('title') ?: $ticket->title}}">
                        @if ($errors->has('title'))
                            <span class="invalid-feedback" role="alert" style="display: block;">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                      </div>
                      <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" id="description" name="description">{{old('title') ?: $ticket->description}}</textarea>
                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert" style="display: block;">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                      </div>

                      <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @if(request()->get('status') == 'closed')
                        Closed Tickets &nbsp; 
                        <a href="{{route('tickets.index')}}" class="btn btn-default btn-sm" style="float:right;"><i class="fa fa-list"></i> Show Open Tickets</a>
                    @else
                        Open Tickets &nbsp; 
                        <a href="{{route('tickets.index',['status'=>'closed'])}}" class="btn btn-default btn-sm" style="float:right;"><i class="fa fa-tasks"></i> Show Closed Tickets</a>
                    @endif
                    <a href="{{route('tickets.create')}}" class="btn btn-default btn-sm" style="float:right;"><i class="fa fa-plus-square"></i> Create Ticket</a>
                </div>

                <div class="card-body">
                   @if($tickets->count() > 0)
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <td style="width: 5%">ID</td>
                                    <td style="width: 25%">Title</td>
                                    <td style="width: 50%">Description</td>
                                    <td style="width: 5%">Status</td>
                                    <td style="width: 15%">Action</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tickets as $ticket)
                                    <tr>
                                        <td>{{$ticket->id}}</td>
                                        <td>{{$ticket->title}}</td>
                                        <td>{{$ticket->description}}</td>
                                        <td>{{$ticket->status}}</td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                            @if($ticket->status == 'open')
                                                <a href="{{route('tickets.edit',['id'=>$ticket->id])}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            @endif
                                            <a href="javascript:;" data-status="{{($ticket->status == 'open') ? 'closed' : 'open'}}" data-url="{{route('tickets.update',['ticket'=>$ticket])}}" class="btn btn-success btn-sm btn-update-ticket"><i class="fa fa-check"></i> Mark as {{($ticket->status == 'open') ? 'Closed' : 'Open'}}</a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                   @else
                        <p>You have no existing open tickets.<br/><a href="{{route('tickets.create')}}">Create new ticket.</a></p>
                   @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection